In [28]:
import pandas as pd
import numpy as np

In [29]:
base_path = '/Users/yutaro/code/data/coxtf/brca_metabric'

In [30]:
clinical_supp_patient_df = pd.read_csv(base_path+'/data_clinical_supp_patient.txt', sep='\t')

In [31]:
clinical_supp_patient_df.head()

,PATIENT_ID,OS_MONTHS,OS_STATUS,VITAL_STATUS,INTCLUST,COHORT,AGE_AT_DIAGNOSIS,LATERALITY,NPI,ER_IHC,INFERRED_MENOPAUSAL_STATE,BREAST_SURGERY,CELLULARITY,HER2_SNP6,THREEGENE,CLAUDIN_SUBTYPE,CHEMOTHERAPY,HORMONE_THERAPY,RADIO_THERAPY,HISTOLOGICAL_SUBTYPE
0,MB-0000,140.500000,LIVING,Living,4ER+,1,75.65,r,6.044,pos,post,MASTECTOMY,NaN,NEUT,ER-/HER2-,claudin-low,NO,YES,YES,IDC
1,MB-0002,84.633333,LIVING,Living,4ER+,1,43.19,r,4.020,pos,pre,BREAST CONSERVING,high,NEUT,ER+/HER2- High Prolif,LumA,NO,YES,YES,IDC
2,MB-0005,163.100000,DECEASED,Died of Disease,3,1,48.87,r,4.030,pos,pre,MASTECTOMY,high,NEUT,NaN,LumB,YES,YES,NO,IDC
3,MB-0006,164.933333,LIVING,Living,9,1,47.68,r,4.050,pos,pre,MASTECTOMY,moderate,NEUT,NaN,LumB,YES,YES,YES,IDC
4,MB-0008,41.366667,DECEASED,Died of Disease,9,1,76.97,r,6.080,pos,post,MASTECTOMY,high,NEUT,ER+/HER2- High Prolif,LumB,YES,YES,YES,IDC

In [32]:
def get_df_marker_expression(datapath):
    metabric_expression = pd.read_csv(datapath, sep=',') 
    metabric_expression = metabric_expression.transpose()
    print("metabric_expression.shape: {}".format(metabric_expression.shape))
    metabric_expression.rename(columns=metabric_expression.iloc[0])
    metabric_expression = metabric_expression.iloc[1:]
    print("metabric_expression.shape: {}".format(metabric_expression.shape))
    return metabric_expression

In [33]:
def get_df_cln(filepath):
    cln_data = pd.read_csv(cln_path, sep='\t')
    cln_selected = cln_data[['ageDiagnosis', 'chemo', 'hormone', 'radiation', 'ER']] 
    d = {'pos': 1, 'neg': 0}
    cln_selected['ER'] = cln_selected['ER'].map(d)
    return cln_selected

In [ ]:
#datapath_rand = '/Users/yutaro/GoogleDrive/github/BayesianFeature/data_preprocessing/metabric_random_subset_plus_oncotype.csv'
#datapath_onco = '/Users/yutaro/GoogleDrive/github/BayesianFeature/data_preprocessing/metabric_oncotype.csv'

In [10]:
datapath_full = '/Users/yutaro/code/data/coxtf/Metabric/metabric_exp.csv' 
cln_path = '/Users/yutaro/code/data/coxtf/Metabric/metabric_cln.txt'

In [9]:
metabric_df = get_df_marker_expression(datapath_full)

metabric_expression.shape: (1982, 49576)
metabric_expression.shape: (1981, 49576)

In [11]:
cln_df = get_df_cln(cln_path)

/Users/yutaro/.pyenv/versions/3.7.2/envs/coxtf/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [12]:
cln_df.head()

         ageDiagnosis  chemo  hormone  radiation  ER
MB-0000         75.65      0        1          1   1
MB-0002         43.19      0        1          1   1
MB-0005         48.87      1        1          0   1
MB-0006         47.68      1        1          1   1
MB-0008         76.97      1        1          1   1

In [13]:
metabric_all = metabric_df.join(cln_df)

In [14]:
metabric_all.head()

,0,1,2,3,4,5,6,7,8,9,...,49571,49572,49573,49574,49575,ageDiagnosis,chemo,hormone,radiation,ER
MB-0000,5.47312,5.93272,6.47903,9.05629,5.79141,5.61412,5.41396,6.67966,6.88893,5.17617,...,5.32622,5.90367,5.52634,5.70785,5.38935,75.65,0,1,1,1
MB-0002,5.34227,5.66568,6.26195,9.63085,6.09273,5.4203,5.38904,6.19411,5.15724,5.34296,...,5.25849,6.18129,5.38761,5.82532,5.38615,43.19,0,1,1,1
MB-0005,5.59965,6.0444,6.19589,9.20463,6.27501,5.41157,5.35322,6.32255,6.4781,5.51469,...,5.44401,5.90272,5.42106,5.5473,5.52566,48.87,1,1,0,1
MB-0006,5.37615,5.88809,6.20598,8.93761,6.0355,5.57762,5.55755,6.32687,6.88582,5.35544,...,5.54597,5.94402,5.5965,5.76726,5.3035,47.68,1,1,1,1
MB-0008,5.28799,5.73392,6.1841,9.27177,6.22722,5.38925,5.43427,6.90009,5.92289,5.57893,...,5.22867,6.09929,5.94612,5.68719,5.4493,76.97,1,1,1,1

In [15]:
metabric_all.shape

(1981, 49581)

In [20]:
def get_h5_data(jared_path, metabric_all, random_state):
    metabric_Time_Event = pd.read_csv(jared_path+'/data_clinical_supp_patient.txt', sep='\t')
    metabric_Time_Event = metabric_Time_Event.set_index('PATIENT_ID')[['OS_MONTHS', 'OS_STATUS']]
    metabric_Time_Event['OS_STATUS'] = (metabric_Time_Event['OS_STATUS'] == 'DECEASED').astype(np.int32)
    
    from sklearn.model_selection import train_test_split
    
    metabric_df = metabric_all.join(metabric_Time_Event)
    
    print(metabric_df.shape)
    
    metabric_df = metabric_df[pd.notnull(metabric_df['OS_MONTHS'])]
    metabric_df = metabric_df[pd.notnull(metabric_df['OS_STATUS'])]
    
    print(metabric_df.shape)
    
    metabric_train_df, metabric_test_df = train_test_split(metabric_df, test_size = 0.2, random_state=123)
    metabric_train_df, metabric_valid_df = train_test_split(metabric_train_df, test_size=0.2, random_state=random_state)
    
    mb_x_train = metabric_train_df.drop(['OS_MONTHS', 'OS_STATUS'], axis = 1).values.astype(np.float32)
    mb_e_train = metabric_train_df['OS_STATUS'].values.astype(np.int32)
    mb_t_train = metabric_train_df['OS_MONTHS'].values.astype(np.float32)
    mb_train = {'x': mb_x_train, 'e': mb_e_train, 't': mb_t_train}

    mb_x_valid = metabric_valid_df.drop(['OS_MONTHS', 'OS_STATUS'], axis = 1).values.astype(np.float32)
    mb_e_valid = metabric_valid_df['OS_STATUS'].values.astype(np.int32)
    mb_t_valid = metabric_valid_df['OS_MONTHS'].values.astype(np.float32)
    mb_valid = {'x': mb_x_valid, 'e': mb_e_valid, 't': mb_t_valid}    

    mb_x_test = metabric_test_df.drop(['OS_MONTHS', 'OS_STATUS'], axis = 1).values.astype(np.float32)
    mb_e_test = metabric_test_df['OS_STATUS'].values.astype(np.int32)
    mb_t_test = metabric_test_df['OS_MONTHS'].values.astype(np.float32)
    mb_test = {'x': mb_x_test, 'e': mb_e_test, 't': mb_t_test}

    metabric_ds = {'train' : mb_train, 'valid': mb_valid ,'test': mb_test}
    
    return metabric_ds

In [19]:
import h5py
def save_dataset(datasets, file):
    f = h5py.File(file)
    for (grp, ds) in datasets.items():
        grp_f = f.create_group(grp)
        for (key, value) in ds.items():
            print('Saving: (%s, %s)' % (grp, key))
            grp_f.create_dataset(key, data=value)
    f.close()

In [27]:
for i in range(5):
    metabric_ds = get_h5_data(base_path, metabric_all, i)  
    save_dataset(metabric_ds, file='/Users/yutaro/code/data/coxtf/metabric_full'+str(i)+'metabric_full_train_valid_test.h5')

(1981, 49583)
(1969, 49583)

/Users/yutaro/.pyenv/versions/3.7.2/envs/coxtf/lib/python3.7/site-packages/ipykernel_launcher.py:3: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  This is separate from the ipykernel package so we can avoid doing imports until

Saving: (train, x)
Saving: (train, e)
Saving: (train, t)
Saving: (valid, x)
Saving: (valid, e)
Saving: (valid, t)
Saving: (test, x)
Saving: (test, e)
Saving: (test, t)
(1981, 49583)
(1969, 49583)
Saving: (train, x)
Saving: (train, e)
Saving: (train, t)
Saving: (valid, x)
Saving: (valid, e)
Saving: (valid, t)
Saving: (test, x)
Saving: (test, e)
Saving: (test, t)
(1981, 49583)
(1969, 49583)
Saving: (train, x)
Saving: (train, e)
Saving: (train, t)
Saving: (valid, x)
Saving: (valid, e)
Saving: (valid, t)
Saving: (test, x)
Saving: (test, e)
Saving: (test, t)
(1981, 49583)
(1969, 49583)
Saving: (train, x)
Saving: (train, e)
Saving: (train, t)
Saving: (valid, x)
Saving: (valid, e)
Saving: (valid, t)
Saving: (test, x)
Saving: (test, e)
Saving: (test, t)
(1981, 49583)
(1969, 49583)
Saving: (train, x)
Saving: (train, e)
Saving: (train, t)
Saving: (valid, x)
Saving: (valid, e)
Saving: (valid, t)
Saving: (test, x)
Saving: (test, e)
Saving: (test, t)

In [24]:
metabric_all.shape

(1981, 49581)